# Generated by Django 5.1.3 on 2024-12-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=models.TextField(default=''),
        ),
    ]
