# Generated by Django 5.1.3 on 2025-01-22 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_additional_info'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
    ]
