# Generated by Django 5.1.3 on 2024-12-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('billing_data', models.JSONField()),
                ('shipping_data', models.JSONField(blank=True, null=True)),
                ('order_data', models.JSONField()),
                ('selected_payment_method', models.CharField(max_length=100)),
                ('coupon_code', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_to_different_address', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
