# Generated by Django 5.1.3 on 2024-12-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='app_orders',
        ),
    ]
