# Generated by Django 5.0.6 on 2024-09-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_image_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='featured',
        ),
    ]
