name: Deploy Django Backend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VPS_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@159.198.66.181 << 'EOF'
            set -e
            cd /var/www/starbound

            # Clone the repo only if it doesn't exist
            if [ ! -d "starbound-backend/.git" ]; then
              rm -rf starbound-backend
              git clone https://github.com/neranjandissanayake/starbound-backend.git
            fi

            cd starbound-backend
            git pull origin main

            # Activate virtual environment (assumes it's already created)
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate

            pip install --upgrade pip
            pip install -r requirements.txt

            python manage.py migrate
            python manage.py collectstatic --noinput

            # Restart Gunicorn (update if you use another WSGI server or service name)
            systemctl restart gunicorn
          EOF
